[[theme]]
name = "smooth"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-smooth/"
commit = "*"
relative_directory = "smooth/"
version = "0.0.1"
leftwm_versions = "*"

[[theme]]
name = "dracula"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-dracula/"
commit = "*"
relative_directory = "dracula/"
version = "0.0.1"
leftwm_versions = "*"