[[theme]]
name = "arise"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-arise/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "db"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-db/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "db-color-dev"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-db-color-dev/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "db-comic"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-db-comic/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "db-nemesis"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-db-nemesis/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "db-scifi"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-db-scifi/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "db-scifi-star"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-db-scifi-star/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "docky"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-docky/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "doublebar"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-doublebar/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "eden"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-eden/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "fancy"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-fancy/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "forest"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-forest/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "grayblocks"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-grayblocks/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "greyblocks"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-greyblocks/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "halo"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-halo/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "material"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-material/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "matrix"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-matrix/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "mesh"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-mesh/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "parker"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-parker/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "pi"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-pi/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "sb-horror"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-sb-horror/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "shades"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-shades/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "smooth"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-smooth/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "space"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-space/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "starwars"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-starwars/"
commit = "*"
version = "3.1.1"
leftwm_versions = ">=0.3.0"
