[[theme]]
name = "eden"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-eden/"
commit = "*"
version = "2.1.4"
leftwm_versions = "*"

[[theme]]
name = "matrix"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-matrix/"
commit = "*"
version = "2.1.4"
leftwm_versions = "*"

[[theme]]
name = "parker"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-parker/"
commit = "*"
version = "2.1.4"
leftwm_versions = "*"

[[theme]]
name = "pi"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-pi/"
commit = "*"
version = "2.1.4"
leftwm_versions = "*"

[[theme]]
name = "smooth"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-smooth/"
commit = "*"
version = "2.1.4"
leftwm_versions = "*"

[[theme]]
name = "space"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-space/"
commit = "*"
version = "2.1.4"
leftwm_versions = "*"

[[theme]]
name = "starwars"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-starwars/"
commit = "*"
version = "2.1.4"
leftwm_versions = "*"
